version: "3.9"

services:

  postgres:
    build: ./postgres
    container_name: vocabulary_postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vocabulary

volumes:
  postgres_data:
